# Top-level configuration
name = "stick-generator"
compatibility_date = "2023-03-13"
account_id = "847aff3ed9c07c12eae4f4747ae61e8b"

workers_dev = false
routes = [
  { pattern = "stick-generator.internal.minutelabs.io", custom_domain = true },
]

r2_buckets  = [
  { binding = "STICK_FIGURES", bucket_name = "stick-figures", preview_bucket_name = "stick-figures-dev" }
]

